/**
 * Test data and configuration for E2E tests
 * Uses environment variables from .env.test (loaded by playwright.config.ts)
 */
export const TestData = {
  users: {
    // Valid user from .env.test (seeded in database)
    valid: {
      id: process.env.E2E_USERNAME_ID || '',
      email: process.env.E2E_USERNAME || '',
      password: process.env.E2E_PASSWORD || '',
    },
    // New user for registration tests (generated dynamically)
    newUser: {
      email: `test.${Date.now()}@example.com`,
      password: 'TestPassword123',
    },
    // Invalid user for negative tests
    invalid: {
      email: 'nonexistent@example.com',
      password: 'wrongpassword',
    },
  },

  planPreferences: {
    // Standard preferences for AI plan generation
    standard: {
      goal: 'hipertrofia',
      system: 'PPL',
      days: ['Poniedziałek', 'Środa', 'Piątek'],
      sessionDuration: 60,
      cycleDuration: 4,
      notes: 'Test plan generated by E2E',
    },
    // Minimal preferences for quick tests
    minimal: {
      goal: 'siła',
      system: 'FBW',
      days: ['Wtorek', 'Czwartek'],
      sessionDuration: 45,
      cycleDuration: 2,
    },
  },

  // Timeouts for various operations
  timeouts: {
    aiGeneration: 60000, // AI generation can take a while
    navigation: 10000,
    animation: 500,
  },
} as const;

/**
 * Helper to validate that required environment variables are set
 */
export function validateTestEnvironment(): void {
  const required = ['E2E_USERNAME', 'E2E_PASSWORD'];
  const missing = required.filter((key) => !process.env[key]);

  if (missing.length > 0) {
    throw new Error(`Missing required environment variables: ${missing.join(', ')}`);
  }
}
