/// <reference types="astro/client" />

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./db/database.types.ts";

declare global {
  namespace App {
    interface Locals {
      supabase: SupabaseClient<Database>;
    }
  }
}

// Environment variables are now configured in astro.config.mjs via env.schema
// Types are auto-generated by Astro and available via "astro:env/server"
